### ISSUE TITLE
[v1.0.0_2015111101] App 第一次啟動 api 呼叫太多

### ISSUE THREAD

**Issue by showsky** [showsky/3tr#1]
180.217.1.248 - - [12/Nov/2015:18:14:10 +0800] "GET /api/place?lat=0.0&lon=0.0&order=distance&distance=date&p=1&c=10 HTTP/1.1" 200 1064 "-" "Dalvik/2.1.0 (Linux; U; Android 5.1.1; C6602 Build/10.7.A.0.222)"
180.217.1.248 - - [12/Nov/2015:18:14:10 +0800] "GET /api/place?lat=0.0&lon=0.0&order=distance HTTP/1.1" 200 1755 "-" "Dalvik/2.1.0 (Linux; U; Android 5.1.1; C6602 Build/10.7.A.0.222)"
180.217.1.248 - - [12/Nov/2015:18:14:11 +0800] "GET /api/place?lat=25.0545559&lon=121.5443276&order=distance&distance=date&p=1&c=10 HTTP/1.1" 200 967 "-" "Dalvik/2.1.0 (Linux; U; Android 5.1.1; C6602 Build/10.7.A.0.222)"
180.217.1.248 - - [12/Nov/2015:18:14:11 +0800] "GET /api/place?lat=25.0545559&lon=121.5443276&order=distance HTTP/1.1" 200 1808 "-" "Dalvik/2.1.0 (Linux; U; Android 5.1.1; C6602 Build/10.7.A.0.222)"
180.217.1.248 - - [12/Nov/2015:18:14:11 +0800] "GET /images/ HTTP/1.1" 403 177 "-" "Dalvik/2.1.0 (Linux; U; Android 5.1.1; C6602 Build/10.7.A.0.222)"
180.217.1.248 - - [12/Nov/2015:18:14:11 +0800] "GET /images/ HTTP/1.1" 403 177 "-" "Dalvik/2.1.0 (Linux; U; Android 5.1.1; C6602 Build/10.7.A.0.222)"
180.217.1.248 - - [12/Nov/2015:18:14:11 +0800] "GET /api/place?lat=25.0545559&lon=121.5443276&order=distance&distance=date&p=1&c=10 HTTP/1.1" 200 967 "-" "Dalvik/2.1.0 (Linux; U; Android 5.1.1; C6602 Build/10.7.A.0.222)"
180.217.1.248 - - [12/Nov/2015:18:14:11 +0800] "GET /images/ HTTP/1.1" 403 177 "-" "Dalvik/2.1.0 (Linux; U; Android 5.1.1; C6602 Build/10.7.A.0.222)"

**Comment by jasonni** [comment]
fixed
