### ISSUE TITLE
臨打記錄是空得

### ISSUE THREAD

**Issue by showsky** [showsky/3tr#11]
透過後端檢查拉取的 API 是有資料，但是在 app 卻沒有資料呈現出來...

![device-2015-12-07-115204](https://cloud.githubusercontent.com/assets/800001/11618672/f98f73ec-9cd8-11e5-877d-57ac6ac29309.png)

**Comment by showsky** [comment]
確定此帳號有臨打記錄

第一次打開 app 進行帳號註冊 -> 臨打記錄是空的.. 

關掉 app 再打開有臨打資料

**Comment by jasonni** [comment]
this bug will fix in version 1.0.1
