### ISSUE TITLE
臨打記錄的報名狀態不對

### ISSUE THREAD

**Issue by showsky** [showsky/3tr#21]
在臨打記錄中，報名記錄有三種 

* 1 => 等待確定
* 2 => 報名成功
* 3 => 報名失敗

![device-2015-12-15-233415](https://cloud.githubusercontent.com/assets/800001/11814934/64f66ec2-a384-11e5-808f-b55ab9690fcb.png)

![2015-12-15_23-32-05](https://cloud.githubusercontent.com/assets/800001/11814935/6559a85c-a384-11e5-91bf-ee47d66fb987.png)

**Comment by jasonni** [comment]
this bug will fix in v1.0.1
