### ISSUE TITLE
[v1.0.0_2015111101]第一次啟動 app 切到第二個分頁(零打列表) 距離不正確

### ISSUE THREAD

**Issue by tedshd** [showsky/3tr#3]
第一次啟動 app 切到第二個分頁(零打列表) 距離不正確
![screenshot_2015-11-12-21-38-44](https://cloud.githubusercontent.com/assets/2949145/11120014/4bcd19ac-8988-11e5-84ca-9a085bba55eb.png)

**Comment by jasonni** [comment]
fixed
